management:
  security:
    enabled: false
    
eureka:
  instance:
    prefer-ip-address: true # Register the IP of the service rather than the host name. preffered for the docker
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/    
 
 


           
