language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - chandresh87@@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- export BUILD_NAME=final-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
env:
  global:
  - secure: Yf12SleSaz9jIEyef/ZG6FSGdylNZloUVcWFvQEMjsDNTtiLfZGEnu05ZzfObGupETo9vNeDxHdXQ/iDWu7wHzdh17y0opD9VnZqWqVp4wv7kkxVYMAAHUkLCj4Wd4ooWWK/R5RSL7GDflp5uGl6fTwDf1+DBHxNOyOF79ggSGGMbYbQo74ggrbD9JgunXU9OfwvDH8K1kRO8eVbX+MxaUX/W88aX+EmYPxNiLwCklIWXR00xZg2L7MwTdHyEmb35zpLDfsYir+oieluwumLbMhKsLnEATp7R7OVxp9yTUQgX3RvT0WjqMvQPb5y1hwVX0uP1QUVGlp2oOKdnzdMnQrj0Lm5Q9wsnCLMPuMGcwcVnJWi0M0lJU/KpODn40gs4b9Pm25uYRmzn6BqnlzOnPglT3qVvaQYCrDABEOHNELFhVLag1bAWZeG7rXwUb/P/tly4awzlee2oA23YjMcZGnMyUP55XOZZnxyU6VcorUAllULF7M4LayWbnPj1Nsehv1MKZHcSvorlF9EhvkXeyjr0lyZOKqnMESKQvS5eSJJZPjvX9PBqx3sYbL52IIdnJuN28FMxGzsWBVnNK3QWReCCuFT/4J262xri/f/C8bPWNPFhEqsxi8P1HageDKHAm9HUYm+WE+t9MpAvx6V+Ge43WMTmuYurPUGREt85Fs=
  - secure: aqnUzA35AjMpRXdP48H6EwdU4sU/Nze8QiR7tpHs+UvI8t0DedEHdVRHF+b3RNNlxHsZ79em8Mm5nRpEXd3ttWf+9m8YPwh57fWmbJkw3zNUMww2LEi8S2K4bzbcEfn40pBh0lFm09KxAEwGKEBN5GaaTPlL7Sm2bBOIhvRy2M5skG/TSb8ibnYMEmM1BT0UXN7A03zPsVezrv1MbrlDfo9P3W0FXJZb754BOcKFX7QFO7fIipMLxQs8iu7J08ihE1so7/IYIyDUIQVzpPdXBT1TNphUzL5kcalsc9JZQGrrkTU7jtjSAtJy1hfTpi0UFucJDGJ4Pc8N84RT4V/u5DeRfX5FYB+AfdYVEBzzEjMsWyOEHyVIfApZDgDEvAAzBvJQTE62ydIdLJ1YDUm3UWOdu32OcAxE+vjS2KKzpLxBB5lR155xjKgeFV0K5EOakR3VE+QXBDrZ5Vb9YWk96VGZefslP0E/m8iALJ/gmfgCcJwSN16J2fD25ajBOAyFvpr+JkgaTk209WPMfK2wNANxWIUopCN9xKpfPgwR7qBUjeUiSD+vydbFhFduSSzRNqnV2bjMHu+DorHF1j9SmBey0p6HqTaR2d0VTbda2cqY/W/0Y3jmPgU2xU/OLP5o59XQOJZOj/d3WwvpHiV82r57EAUQYKwecfOfXyc7y0A=
