version: '2.1'
services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
  eurekaserver:
    image: chandreshmishra/eurekaservice:latest
    ports:
       - "8761:8761"
    environment:
       EUREKA_USERNAME: "eureka-user"
       EUREKA_PASSWORD: "eureka-password"
       
  configserver:
    image: com.microservicePlayground/configservice:latest
    depends_on:
      - rabbitmq
    ports:
       - "8888:8888" 
    links:
       - "eurekaserver:eurekaserver"
       - "rabbitmq:rabbitmq"
    environment:
      EUREKA_USERNAME: "eureka-user"
      EUREKA_PASSWORD: "eureka-password"
      EUREKASERVER_URI: "http://EUREKA_USERNAME:EUREKA_PASSWORD@eurekaserver:8761/eureka/"
      RABBITMQ_SERVICE_HOST: rabbitmq
      RABBITMQ_SERVICE_PORT: 5672
      RABBITMQ_SERVICE_USERNAME: guest
      RABBITMQ_SERVICE_PASSWORD: guest