version: '2'
services:
  configserver:
    image: com.microservicePlayground/configservice:1.0
    ports:
       - "8888:8888"
    environment:
      ENCRYPT_KEY:       "IMSYMMETRIC"   
    #service: configserver
    
  personservice:
    image: com.microservicePlayground/personmicroservice:1.0
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
