version: '2'
services:

  eurekaserver:
     image: com.microservicePlayground/eurekaservice:1.0
     ports:
       - "8761:8761"
       
  configserver:
    image: com.microservicePlayground/configservice:1.0
    ports:
       - "8888:8888"
    environment:
      ENCRYPT_KEY: "IMSYMMETRIC"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
   
    
  personservice:
    image: com.microservicePlayground/personmicroservice:1.0
    ports:
      - "8080:8080"
    environment:
        PROFILE: "dev"
        SERVER_PORT: "8080"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        ENCRYPT_KEY:       "IMSYMMETRIC"

   
  organizationservice:
    image: com.microservicePlayground/organizationmicroservice:1.0
    ports:
       - "8085:8085"
    environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        ENCRYPT_KEY:       "IMSYMMETRIC"
        
        
  organizationservice2:
    
    image: com.microservicePlayground/organizationmicroservice:1.0
    ports:
        - "8086:8086"
    environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        ENCRYPT_KEY:       "IMSYMMETRIC"
        
  turbineservice:
    image: com.microservicePlayground/turbinemicroservice:1.0
    ports:
      - "8989:8989"
    environment:
        PROFILE: "default"
        SERVER_PORT: "8989"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        ENCRYPT_KEY:       "IMSYMMETRIC"      