server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
        
management.security.enabled: false
#
#
#  debug:
#    request: true
#
#zuul:
#  ignored-services: '*'
#  prefix:  /api
#  routes:
#      personservice: /personservice/**
#      organizationservice:  /orgservice/**
