server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # Don’t register with Eureka service.
    fetch-registry: false # Don’t cache registry information locally.
    service-url:
      defaultZone:  http://admin:pwd@localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 5   #Initial time to wait before server takes requests

spring:
  security:
    user:
      name: eureka-user
      password: eureka-pass
      
         